specfile_path: CI/fapolicyd.spec

upstream_package_name: fapolicyd
downstream_package_name: fapolicyd


jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - epel-8
