specfile_path: ci.spec

upstream_package_name: fapolicyd
downstream_package_name: fapolicyd
upstream_tag_template: v{version}


jobs:
- job: tests
  trigger: pull_request
  targets:
    - fedora-all
    - epel-8
