specfile_path: CI/fapolicyd.spec

upstream_package_name: fapolicyd
downstream_package_name: fapolicyd
upstream_tag_template: v{version}


jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-rawhide
      - epel-9
      - epel-8
