specfile_path: fapolicyd.spec

upstream_package_name: fapolicyd
downstream_package_name: fapolicyd
upstream_tag_template: v{version}

actions:
    post-upstream-clone:
      - bash -c "curl -o fapolicyd-selinux-0.4.tar.gz https://github.com/linux-application-whitelisting/fapolicyd-selinux/archive/refs/tags/v0.4.tar.gz"
      - bash -c "curl -o uthash-2.3.0.tar.gz https://github.com/troydhanson/uthash/archive/refs/tags/v2.3.0.tar.gz"

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-rawhide
      - epel-9
      - epel-8
